language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  - npm i -g howardroark/pollinate#feature/keep-history
before_script:
  - git config --global user.email "jedwards@fastmail.com"
  - git config --global user.name "Andy Edwards"
  - npm prune
script:
  - cat ./pollinated/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

