language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  - npm i -g howardroark/pollinate#feature/keep-history
  - git config --global user.email "jedwards@fastmail.com"
  - git config --global user.name "Andy Edwards"
before_script:
  - npm prune
after_script:
  - cd pollinated && cat coverage/lcov.info | node_modules/bin/coveralls.js

